setwd("D:\\Vytenio_f\\Online_courses\\Coursera\\Data_science\\Exploratory_Data_Analysis\\Week1")
data <- read.table(file="household_power_consumption.txt", header = TRUE, sep = ";",
colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric")
, na.strings="?")
data$full_date <- paste(data$Date, data$Time)
data$Date <- strptime(data$Date, "%d/%m/%Y")
data$Time <- strptime(data$Time, "%H:%M:%S")
data$full_date <- strptime(data$full_date, "%d/%m/%Y %H:%M:%S")
data <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
png("plot3.png")
plot(data$full_date, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(data$full_date, data$Sub_metering_2, col="red")
lines(data$full_date, data$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty = c(1, 1, 1), pch=c(NA,NA,NA))
dev.off()
